### ISSUE TITLE
Document the code

### ISSUE THREAD

**Issue by sIldefonsoRR** [runtimerevolution/labs#79]
The idea is to create code documentation.

An example, is to use pDoc https://pdoc.dev/ 
Here is an example: https://sergio-ildefonso.medium.com/how-to-document-python-code-bccc7d081337

Note: It can be another one.

**Comment by ctmartinez1992** [comment]
This kind of documentation is not very interesting for most of the code. It's only interesting for API endpoints, but since we are already using FastAPI. That already makes a swagger page available on the /docs URL.

So we are closing this issue because it's not necessary to add another tool for comments.
